## TravisCI config
#
language: python
python:
  - "3.3"
  - "3.4"
  
before_install:
    ## From: http://conda.pydata.org/docs/travis.htm
    ## Another one: https://gist.github.com/dan-blanchard/7045057
    #- sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a	## Useful for debugging any conda issues
  
    - deps="`grep -v \# conda_requirements.txt`"
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION $deps
    - source activate test-environment

install:
  - python setup.py install

script:
    #- python setup.py doctest_docs
    - nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS,+REPORT_UDIFF \
                        --tests=README.rst \
                        --doctest-extension=.rst
    #- python setup.py doctest_code
    - nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE,+ELLIPSIS,+REPORT_NDIFF \
                        --tests=fuefit.processor,fuefit.datamodel,fuefit.pdcalc
    #- python setup.py test_code
    - nosetests
 
#   #- python setup.py test_code_cover

    - python setup.py build_sphinx                  ## Build html-docs.
    - python setup.py sdist bdist_wheel             ## Create archives for PyPI repo.

    ## Ensure README valid ReST for PyPI.
    ##  In case it fails, improve the filtering-code in ``setup.py``.
    - python setup.py --long-description | rst2html.py  --halt=warning > /dev/null

#after_success:
#    coveralls

branches:
    only:
        - master

deploy:
    provider: pypi
    user: ankostis
    password:
        secure: AFaWbL5FIQHTAKxmFnOId1rApOsHxjpWGP3RVXTKjw65SJnRDoExne6Zd+M5ATRryBh2ud2ea3JK96mOl/CAZpr7fTpMHMnRruhyyQvJNKmOrXKBASmDF0yXoxuEaDNGO8BJ9sa0+S7sdoRiR/AzuDzRPHPzFR5J5DQiGCMHqmU=
    on:
        tags: true
